# Generated by Django 3.2.3 on 2021-05-28 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userdata',
        ),
    ]
